### ISSUE TITLE
No such file or directory: '/data/eng_train.segmentation.csv'

### ISSUE THREAD

**Issue by kaishaoshao** [sharpsy/llm-morphological-segmenter#1]
Can't find this data file, my data directory generation is empty. 
```
llm) shaokai@King:llm-morphological-segmenter(main)$ make all
mkdir -p out/llm-segm
docker run --rm --env HF_ENDPOINT=https://hf-mirror.com --env HF_HOME=/out/.cache --env PYTHONUNBUFFERED=1 --env PYTHONDONTWRITEBYTECODE=1 --env SENTENCE_TRANSFORMERS_HOME='/out/.cache/sent-trans' --env HF_DATASETS_CACHE="/out/.cache/datasets" -v $(realpath data):/data -v $(realpath src):/app -v $(realpath out):/out  llm-morphological-segmenter python /app/main.py
touch out/.run.sentinel
Some weights of XLMRobertaForSequenceClassification were not initialized from the model checkpoint at cis-lmu/glot500-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
The new embeddings will be initialized from a multivariate normal distribution that has old embeddings' mean and covariance. As described in this article: https://nlp.stanford.edu/~johnhew/vocab-expansion.html. To disable this, use `mean_resizing=False`
Traceback (most recent call last):
  File "/app/main.py", line 174, in <module>
    data_train, data_dev, data_test = load_lang_data(lang)
  File "/app/main.py", line 114, in load_lang_data
    data_train = pd.read_csv(f"{fname_px}_train.segmentation.csv", header=None)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/usr/local/lib/python3.10/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/data/eng_train.segmentation.csv'
```

**Comment by kaishaoshao** [comment]
finish
